spring:
    application:
        name: shop-service
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8081/realms/shop-service-realm
                    jwk-set-uri: http://localhost:8081/realms/shop-service-realm/protocol/openid-connect/certs
